# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CoderZeaho/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
target 'WJKVideoPlayerDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WJKVideoPlayerDemo

pod 'Masonry', '~> 1.0.2'
pod 'CategoryKit-Additions', '~> 1.0.0'

end
